=== grobm10/XmlEngine/Docs/entities.dtd
<!--
   Projects folder structure DTD

   $Revision: 0.1 $
   $Date: 2012/06/01 12:00:00 $
-->

<!ELEMENT entities (entity*)>
	<!ELEMENT entity (table, pk, fields)>
	<!ATTLIST entity name CDATA #REQUIRED>
		<!ELEMENT table EMPTY>
		<!ATTLIST table name CDATA #REQUIRED 
						autoincrement CDATA #REQUIRED>
						
		<!ELEMENT pk (field+)>
		<!ELEMENT fields (field+)>
			<!ELEMENT field EMPTY>
			<!ATTLIST field name CDATA #REQUIRED
							type CDATA #IMPLIED
							required CDATA #IMPLIED
							length CDATA #IMPLIED>

=== grobm10/XmlEngine/Docs/entities.xml
<?xml version="1.0"?><!DOCTYPE entities SYSTEM "entities.dtd"><entities>    <entity name="Bundle">		<table name="bundles" autoincrement="true" />		<pk>			<field name="id" />		</pk>		<fields>			<field name="id" type="int" required="true" />			<field name="video" type="Video" required="true" />			<field name="language" type="Language" required="true" />			<field name="region" type="Region" required="true" />			<field name="partner" type="Partner" required="true" />			<field name="entityId" type="string" required="false" length="255" />		</fields>	</entity>    <entity name="Language">		<table name="languages" autoincrement="false" />		<pk>			<field name="code" />		</pk>		<fields>			<field name="code" type="string" required="true" length="3" />			<field name="alt" type="string" required="true" length="2" />			<field name="name" type="string" required="true" length="255" />		</fields>	</entity>    <entity name="Log">		<table name="logs" autoincrement="true" />		<pk>			<field name="id" />		</pk>		<fields>			<field name="id" type="int" required="true" />			<field name="process" type="Process" required="true" />			<field name="description" type="string" required="true" length="1023" />			<field name="isError" type="bool" required="true" />		</fields>	</entity>    <entity name="Metadata">		<table name="metadata" autoincrement="true" />		<pk>			<field name="id" />		</pk>		<fields>			<field name="id" type="int" required="true" />			<field name="airDate" type="string" required="false" length="255" />			<field name="archiveStatus" type="string" required="false" length="255" />			<field name="assetGUID" type="string" required="false" length="255" />			<field name="assetID" type="int" required="false" />			<field name="author" type="string" required="false" length="255" />			<field name="category" type="string" required="false" length="255" />			<field name="copyrightHolder" type="string" required="false" length="255" />			<field name="description" type="text" required="false" />			<field name="dTOAssetXMLExportstage1" type="bool" required="false" />			<field name="dTOContainerPosition" type="string" required="false" length="255" />			<field name="dTOCopyrightHolder" type="string" required="false" length="255" />			<field name="dTOEpisodeID" type="string" required="true" length="255" />			<field name="dTOEpisodeName" type="string" required="false" length="255" />			<field name="dTOGenre" type="string" required="false" length="255" />			<field name="dTOLongDescription" type="text" required="false" />			<field name="dTOLongEpisodeDescription" type="text" required="false" />			<field name="dTORatings" type="string" required="false" length="255" />			<field name="dTOReleaseDate" type="string" required="false" length="255" />			<field name="dTOSalesPrice" type="string" required="false" length="255" />			<field name="dTOSeasonID" type="string" required="true" length="255" />			<field name="dTOSeasonName" type="string" required="false" length="255" />			<field name="dTOSeriesDescription" type="text" required="false" />			<field name="dTOSeriesID" type="string" required="true" length="255" />			<field name="dTOShortEpisodeDescription" type="text" required="false" />			<field name="dTOShortDescription" type="text" required="false" />			<field name="eMDeliveryAsset" type="bool" required="false" />			<field name="episodeName" type="string" required="false" length="255" />			<field name="episodeNumber" type="int" required="true" />			<field name="forceDTOexportXML" type="bool" required="false" />			<field name="forceDTOproxyAsset" type="bool" required="false" />			<field name="genre" type="string" required="false" length="255" />			<field name="keywords" type="string" required="false" length="255" />			<field name="licenseStartDate" type="string" required="false" length="255" />			<field name="localEntity" type="bool" required="false" />			<field name="location" type="string" required="false" length="255" />			<field name="mediaType" type="string" required="false" length="255" />			<field name="metadataSet" type="string" required="false" length="255" />			<field name="network" type="string" required="true" length="255" />			<field name="owner" type="string" required="false" length="255" />			<field name="ratingsOverride" type="string" required="false" length="255" />			<field name="ratingSystem" type="string" required="false" length="255" />			<field name="releaseYear" type="string" required="false" length="255" />			<field name="seasonDescription" type="text" required="false" />			<field name="seasonLanguage" type="string" required="false" length="255" />			<field name="seasonName" type="string" required="false" length="255" />			<field name="seasonNumber" type="string" required="false" length="255" />			<field name="seasonOverride" type="string" required="false" length="255" />			<field name="seriesDescription" type="text" required="false" />			<field name="seriesName" type="string" required="true" length="255" />			<field name="status" type="string" required="false" length="255" />			<field name="storeandtrackversionsofthisasset" type="bool" required="false" />			<field name="syndicationPartnerDelivery" type="string" required="false" length="255" />			<field name="title" type="string" required="false" length="255" />			<field name="tVRating" type="string" required="false" length="255" />		</fields>	</entity>    <entity name="Partner">		<table name="partners" autoincrement="true" />		<pk>			<field name="id" />		</pk>		<fields>			<field name="id" type="int" required="true" />			<field name="name" type="string" required="true" length="255" />		</fields>	</entity>    <entity name="Process">		<table name="processes" autoincrement="true" />		<pk>			<field name="id" />		</pk>		<fields>			<field name="id" type="int" required="true" />			<field name="type" type="Type" required="true" />			<field name="state" type="State" required="true" />			<field name="processDate" type="date" required="true" />			<field name="bundle" type="Bundle" required="false" />			<field name="issues" type="string" required="false" length="4096" />		</fields>	</entity>    <entity name="Region">		<table name="regions" autoincrement="false" />		<pk>			<field name="code" />		</pk>		<fields>			<field name="code" type="string" required="true" length="2" />			<field name="country" type="string" required="true" length="255" />			<field name="language" type="Language" required="true" />		</fields>	</entity>    <entity name="Role">		<table name="roles" autoincrement="true" />		<pk>			<field name="id" />		</pk>		<fields>			<field name="id" type="int" required="true" />			<field name="name" type="string" required="true" length="255" />		</fields>	</entity>    <entity name="State">		<table name="states" autoincrement="true" />		<pk>			<field name="id" />		</pk>		<fields>			<field name="id" type="int" required="true" />			<field name="name" type="string" required="true" length="255" />		</fields>	</entity>    <entity name="Type">		<table name="types" autoincrement="true" />		<pk>			<field name="id" />		</pk>		<fields>			<field name="id" type="int" required="true" />			<field name="name" type="string" required="true" length="255" />		</fields>	</entity>    <entity name="User">		<table name="users" autoincrement="false" />		<pk>			<field name="id" />		</pk>		<fields>			<field name="id" type="string" required="true" length="32" />			<field name="password" type="string" required="true" length="32" />			<field name="name" type="string" required="true" length="255" />			<field name="lastActionDate" type="date" required="true" />			<field name="role" type="Role" required="true" />			<field name="active" type="bool" required="true" />		</fields>	</entity>    <entity name="Video">		<table name="videos" autoincrement="true" />		<pk>			<field name="id" />		</pk>		<fields>			<field name="id" type="int" required="true" />			<field name="metadata" type="Metadata" required="true" />			<field name="audioCodec" type="string" required="false" length="255" />			<field name="createdBy" type="string" required="false" length="255" />			<field name="creationDate" type="date" required="false" />			<field name="dTOVideoType" type="string" required="false" length="255" />			<field name="duration" type="string" required="false" length="255" />			<field name="fileCreateDate" type="date" required="false" />			<field name="fileModificationDate" type="date" required="false" />			<field name="fileName" type="string" required="true" length="255" />			<field name="imageSize" type="string" required="false" length="255" />			<field name="lastAccessed" type="date" required="false" />			<field name="lastModified" type="date" required="false" />			<field name="mD5Hash" type="string" required="true" length="255" />			<field name="mD5HashRecal" type="bool" required="false" />			<field name="mimeType" type="string" required="false" length="255" />			<field name="size" type="string" required="true" length="255" />			<field name="storedOn" type="string" required="false" length="255" />			<field name="timecodeOffset" type="string" required="false" length="255" />			<field name="videoBitrate" type="string" required="false" length="255" />			<field name="videoCodec" type="string" required="false" length="255" />			<field name="videoElements" type="string" required="false" length="255" />			<field name="videoFrameRate" type="string" required="false" length="255" />		</fields>	</entity></entities>
