=== grobm10/XmlEngine/Docs/folders.dtd
<!--
   Projects folder structure DTD

   $Revision: 0.1 $
   $Date: 2012/06/01 12:00:00 $
-->

<!ELEMENT folders (folder+)>
	<!ELEMENT folder (folder*)>
	<!ATTLIST folder name CDATA #REQUIRED>

=== grobm10/XmlEngine/Docs/folders.xml
<?xml version="1.0"?><!DOCTYPE folders SYSTEM "folders.dtd"><folders>    <folder name="Docs" />    <folder name="Entities" />    <folder name="Models" />    <folder name="resources">   		<folder name="css" />   		<folder name="img" />   		<folder name="js">   			<folder name="controllers" />   			<folder name="entities" />   			<folder name="models" />   			<folder name="utils" />   			<folder name="views" />   		</folder>    </folder>    <folder name="Utils" />    <folder name="Views" /></folders>
