=== grobm10/XmlEngine/Docs/inserts.dtd
<!--
   Projects folder structure DTD

   $Revision: 0.1 $
   $Date: 2012/06/01 12:00:00 $
-->

<!ELEMENT inserts (entries*)>
	<!ELEMENT entries (entry*)>
	<!ATTLIST entries table CDATA #REQUIRED>
		<!ELEMENT entry (field+)>
			<!ELEMENT field (#PCDATA)>
			<!ATTLIST field name CDATA #REQUIRED>

=== grobm10/XmlEngine/Docs/inserts.xml
<?xml version="1.0"?>
<!DOCTYPE inserts SYSTEM "inserts.dtd">

<inserts>
	<entries table="bundles">
		<entry>
			<field name="id">1</field>
			<field name="videoId">1</field>
			<field name="languageCode">ENG</field>
			<field name="regionCode">UK</field>
			<field name="partnerId">1</field>
			<field name="entityId">NULL</field>
		</entry>
		<entry>
			<field name="id">2</field>
			<field name="videoId">2</field>
			<field name="languageCode">ENG</field>
			<field name="regionCode">UK</field>
			<field name="partnerId">1</field>
			<field name="entityId">NULL</field>
		</entry>
		<entry>
			<field name="id">3</field>
			<field name="videoId">3</field>
			<field name="languageCode">ENG</field>
			<field name="regionCode">UK</field>
			<field name="partnerId">1</field>
			<field name="entityId">NULL</field>
		</entry>
	</entries>
	<entries table="languages">
		<entry>
			<field name="code">DEU</field>
			<field name="alt">DE</field>
			<field name="name">GERMAN</field>
		</entry>
		<entry>
			<field name="code">ENG</field>
			<field name="alt">EN</field>
			<field name="name">ENGLISH</field>
		</entry>
		<entry>
			<field name="code">FRE</field>
			<field name="alt">FR</field>
			<field name="name">FRENCH</field>
		</entry>
		<entry>
			<field name="code">ITA</field>
			<field name="alt">IT</field>
			<field name="name">ITALIAN</field>
		</entry>
		<entry>
			<field name="code">JPN</field>
			<field name="alt">JP</field>
			<field name="name">JAPANESE</field>
		</entry>
		<entry>
			<field name="code">SPA</field>
			<field name="alt">ES</field>
			<field name="name">SPANISH</field>
		</entry>
	</entries>
	<entries table="logs">
		<entry>
			<field name="id">1</field>
			<field name="processId">1</field>
			<field name="description">"checksum" required for iTunes</field>
			<field name="isError">0</field>
		</entry>
		<entry>
			<field name="id">2</field>
			<field name="processId">1</field>
			<field name="description">"copyright_cline" required for iTunes</field>
			<field name="isError">0</field>
		</entry>
		<entry>
			<field name="id">3</field>
			<field name="processId">3</field>
			<field name="description">The given md5 value was wrong. Real value: 96bc60f1d5dd14342dc220cdad8dc7d9</field>
			<field name="isError">1</field>
		</entry>
	</entries>
	<entries table="metadata">
		<entry>
			<field name="id">1</field>
			<field name="airDate">2011-08-02</field>
			<field name="archiveStatus">NULL</field>
			<field name="assetGUID">NULL</field>
			<field name="assetID">NULL</field>
			<field name="author">NULL</field>
			<field name="category">NULL</field>
			<field name="copyrightHolder">2011 Viacom Inc.</field>
			<field name="description">NULL</field>
			<field name="dTOAssetXMLExportstage1">0</field>
			<field name="dTOContainerPosition">1</field>
			<field name="dTOCopyrightHolder">2011 Viacom Inc.</field>
			<field name="dTOEpisodeID">UK_NICKELODEON_WINXCLUB_101</field>
			<field name="dTOEpisodeName">Winx Club</field>
			<field name="dTOGenre">NULL</field>
			<field name="dTOLongDescription">Embark on a fantasy adventure with Bloom, Stella, Flora, Musa, Tecna and Aisha, the Winx Club! a special group of friends with strength, beauty, and magic in their wings! In this feature-length special, join Bloom, Stella and the fairies of Alfea College as they learn to use their powers to battle evil and save the world! The Winx Club takes the girl power to new heights, with six great friends who not only do good, but they look great!</field>
			<field name="dTOLongEpisodeDescription">Embark on a fantasy adventure with Bloom, Stella, Flora, Musa, Tecna and Aisha, the Winx Club! a special group of friends with strength, beauty, and magic in their wings! In this feature-length special, join Bloom, Stella and the fairies of Alfea College as they learn to use their powers to battle evil and save the world! The Winx Club takes the girl power to new heights, with six great friends who not only do good, but they look great!</field>
			<field name="dTORatings">NULL</field>
			<field name="dTOReleaseDate">2011-08-02</field>
			<field name="dTOSalesPrice">NULL</field>
			<field name="dTOSeasonID">UK_NICKELODEON_WINXCLUB_1</field>
			<field name="dTOSeasonName">NULL</field>
			<field name="dTOSeriesDescription">NULL</field>
			<field name="dTOSeriesID">UK_NICKELODEON_WINXCLUB</field>
			<field name="dTOShortEpisodeDescription">Embark on a fantasy adventure with Bloom, Stella, Flora, Musa, Tecna and Aisha, the Winx Club! a special group of friends with strength, beauty, and magic in their wings! In this feature-length special, join Bloom, Stella and the fairies of Alfea College as they learn to use their powers to battle evil and save the world! The Winx Club takes the girl power to new heights, with six great friends who not only do good, but they look great!</field>
			<field name="dTOShortDescription">Embark on a fantasy adventure with Bloom, Stella, Flora, Musa, Tecna and Aisha, the Winx Club! a special group of friends with strength, beauty, and magic in their wings! In this feature-length special, join Bloom, Stella and the fairies of Alfea College as they learn to use their powers to battle evil and save the world! The Winx Club takes the girl power to new heights, with six great friends who not only do good, but they look great!</field>
			<field name="eMDeliveryAsset">0</field>
			<field name="episodeName">Winx Club</field>
			<field name="episodeNumber">1</field>
			<field name="forceDTOexportXML">0</field>
			<field name="forceDTOproxyAsset">0</field>
			<field name="genre">NULL</field>
			<field name="keywords">NULL</field>
			<field name="licenseStartDate">2011-08-02</field>
			<field name="localEntity">0</field>
			<field name="location">NULL</field>
			<field name="mediaType">NULL</field>
			<field name="metadataSet">NULL</field>
			<field name="network">NICKELODEON</field>
			<field name="owner">NULL</field>
			<field name="ratingsOverride">NULL</field>
			<field name="ratingSystem">NULL</field>
			<field name="releaseYear">2011-08-02</field>
			<field name="seasonDescription">NULL</field>
			<field name="seasonLanguage">en-GB</field>
			<field name="seasonName">NULL</field>
			<field name="seasonNumber">1</field>
			<field name="seasonOverride">NULL</field>
			<field name="seriesDescription">NULL</field>
			<field name="seriesName">WINXCLUB</field>
			<field name="status">NULL</field>
			<field name="storeandtrackversionsofthisasset">0</field>
			<field name="syndicationPartnerDelivery">NULL</field>
			<field name="title">NULL</field>
			<field name="tVRating"></field>
		</entry>
		<entry>
			<field name="id">2</field>
			<field name="airDate">2011-08-02</field>
			<field name="archiveStatus">NULL</field>
			<field name="assetGUID">NULL</field>
			<field name="assetID">NULL</field>
			<field name="author">NULL</field>
			<field name="category">NULL</field>
			<field name="copyrightHolder">2011 Viacom Inc.</field>
			<field name="description">NULL</field>
			<field name="dTOAssetXMLExportstage1">0</field>
			<field name="dTOContainerPosition">2</field>
			<field name="dTOCopyrightHolder">2011 Viacom Inc.</field>
			<field name="dTOEpisodeID">UK_NICKELODEON_WINXCLUB_102</field>
			<field name="dTOEpisodeName">Winx Club: Revenge of the Trix</field>
			<field name="dTOGenre">NULL</field>
			<field name="dTOLongDescription">Bloom, Stella, Flora, Musa and Tecna are back with more otherworldy adventures in Winx Club: Revenge of the Trix! Bloom?s home on her first school break, but the weird dreams she was having back at Alfea have come with her. And these dreams are trying to tell her something important! Good thing her fellow Winx have vowed to help Bloom learn what they mean. In the meantime, Bloom is learning about her home planet, her birth parents and her powers; Sky and Bloom are falling for each other, but Sky is supposed to marry Princess Diaspro; the evil Trix want something only Bloom has, so they follow her to Gardenia and will not leave without it! Will there be a showdown between Bloom and Diaspro? What will the other Winx find out about Bloom? Will the Trix finally get what they?re after? So hang on, because it?s all revealed here, in the magical, fantastical Winx Club: Revenge of the Trix!</field>
			<field name="dTOLongEpisodeDescription">Bloom, Stella, Flora, Musa and Tecna are back with more otherworldy adventures in Winx Club: Revenge of the Trix! Bloom?s home on her first school break, but the weird dreams she was having back at Alfea have come with her. And these dreams are trying to tell her something important! Good thing her fellow Winx have vowed to help Bloom learn what they mean. In the meantime, Bloom is learning about her home planet, her birth parents and her powers; Sky and Bloom are falling for each other, but Sky is supposed to marry Princess Diaspro; the evil Trix want something only Bloom has, so they follow her to Gardenia and will not leave without it! Will there be a showdown between Bloom and Diaspro? What will the other Winx find out about Bloom? Will the Trix finally get what they?re after? So hang on, because it?s all revealed here, in the magical, fantastical Winx Club: Revenge of the Trix!</field>
			<field name="dTORatings">NULL</field>
			<field name="dTOReleaseDate">2011-08-02</field>
			<field name="dTOSalesPrice">NULL</field>
			<field name="dTOSeasonID">UK_NICKELODEON_WINXCLUB_1</field>
			<field name="dTOSeasonName">NULL</field>
			<field name="dTOSeriesDescription">NULL</field>
			<field name="dTOSeriesID">UK_NICKELODEON_WINXCLUB</field>
